# INTRO TO PYTHON

Python is one of the most popular programming languages for data science, machine learning and artificial intelligence.

## 1. ARITHMETIC AND VARIABLES

### 1.1. Printing

In Python, we ask a computer to print a message for us by writing print() and putting the message inside the parentheses and enclosed in quotation marks.

In [1]:
print("Hello world")

Hello world


### 1.2. Arithmetic

We can also print the value of some arithmetic operation (such as addition, subtraction, multiplication, or division).

Note that unlike when we were simply printing text, we don't use any quotation marks.

In [2]:
print(1 + 2)

3


You can actually do a lot of calculations with python! See the table below for some examples.

| Operation	        | Symbol    | Example       |
|-------------------|-----------|---------------|
| Addition	        | +	        | 1 + 2 = 3     |
| Subtraction	    | -	        | 5 - 4 = 1     |
| Multiplication    | *	        | 2 * 4 = 8     |
| Division	        | /	        | 6 / 3 = 2     |
| Exponent	        | **	    | 3 ** 2 = 9    |


You can control the order of operations in long calculations with parentheses.

In [3]:
print(((1 + 3) * (9 - 2) / 2) ** 2)

196.0


In general, Python follows the PEMDAS rule when deciding the order of operations.

### 1.3. Comments

We use comments to annotate what code is doing. They help other people to understand your code, and they can also be helpful if you haven't looked at your own code in a while. 

To indicate to Python that a line is comment (and not Python code), you need to write a pound sign (#) as the very first character.

Once Python sees the pound sign and recognizes that the line is a comment, it is completely ignored by the computer.

In [7]:
# Multiply 3 by 2
print(3 * 2)

6


### 1.4. Variables

#### Creating variables

In general, to work with a variable, you need to begin by selecting the name you want to use. They need to satisfy several requirements:
- They can't have spaces
- They can only include letters, numbers, and underscores
- They have to start with a letter or underscore

Then, to create the variable, you need to use = to assign the value that you want it to have.
You can always take a look at the value assigned to the variable by using print() and putting the name of the variable in parentheses.

In [4]:
# Create a variable called test_var and give it a value of 4+5
test_var = 4 + 5

# Print the value of test_var
print(test_var)

9


#### Manipulating variables

You can always change the value assigned to a variable by overriding the previous value.

In [6]:
# Set the value of a new variable to 3
my_var = 3

# Print the value assigned to my_var
print(my_var)

# Change the value of the variable to 100
my_var = 100

# Print the new value assigned to my_var
print(my_var)

3
100


Note that in general, whenever you define a variable in a code cell, all of the code cells that follow also have access to the variable.

The next code cell tells Python to increase the current value of my_var by 3.

To do this, we still need to use my_var = like before. And also just like before, the new value we want to assign to the variable is to the right of the = sign.

In [8]:
# Increase the value by 3
my_var = my_var + 3

# Print the value assigned to my_var
print(my_var)

103


## Exercise 1

### Question 1

Next, you will run some code from the tutorial, so you can see how it works for yourself.  Run the next code cell without changes.

You just ran code to print `Hello world!`, which you should see in the output above.

In [9]:
print("Hello, world!")

Hello, world!


### Question 2

Now, you will print another message of your choosing. To do this, change `print("Your message here!")` to use a different message. For instance, you might like to change it to something like:

Make sure that your message is enclosed in quotation marks (`"`), and the message itself does not use quotation marks.

In [10]:
# TODO: Change the message
print("Start learning!")

Start learning!


### Question 3

As you learned in the tutorial, a comment in Python has a pound sign (`#`) in front of it, which tells Python to ignore the text after it.

Putting a pound sign in front of a line of code will make Python ignore that code. For instance, this line would be ignored by Python. When we remove the pound sign in front of a line of code, we call this uncommenting.

In this problem, you will uncomment two lines in the code cell below and view the output:
- Remove the `#` in front of `q3.hint()`. To avoid errors, do NOT remove the `#` in front of `# Uncomment to view hint`. 
- Next, remove the `#` in front of `q3.solution()`.

In [ ]:
# Uncomment to get a hint
q3.hint()

# Uncomment to view solution
q3.solution()

`Hint`: If you're ever stuck on a question, it's a good idea to look at the hint before viewing the solution.

`Solution`: If you're still stuck on a question after viewing the hint and re-reading the tutorial, you can view the solution. You can also view the solution after you have successfully submitted your own answer, to check if the official solution is any different (there may be more than one right answer!).

### Question 4

In the tutorial, you defined several variables to calculate the total number of seconds in a year. Run the next code cell to do the calculation here.

In [11]:
# Create variables
num_years = 4
days_per_year = 365 
hours_per_day = 24
mins_per_hour = 60
secs_per_min = 60

# Calculate number of seconds in four years
total_secs = secs_per_min * mins_per_hour * hours_per_day * days_per_year * num_years
print(total_secs)

126144000


Use the next code cell to:
- Define a variable `births_per_min` and set it to 250. (There are on average 250 babies born each minute.)
- Define a variable `births_per_day` that contains the average number of babies born each day. (To set the value of this variable, you should use `births_per_min` and some of the variables from the previous code cell.)

In [12]:
# TODO: Set the value of the births_per_min variable
births_per_min = 250

# TODO: Set the value of the births_per_day variable
births_per_day = births_per_min * mins_per_hour * hours_per_day

### Question 5

The Titanic competition is Kaggle's most famous data science competition. In this competition, participants are challenged to build a machine learning model that can predict whether or not passengers survived the Titanic shipwreck, based on information like age, sex, family size, and ticket number.

Run the next code cell without changes to load and preview the `titanic data`.

Don't worry about the details of the code for now - the end result is just that the all of the titanic data has been loaded in a variable named titanic_data.

In [ ]:
# Load the data from the titanic competition
import pandas as pd
titanic_data = pd.read_csv("../input/titanic/train.csv")

# Show the first five rows of the data
titanic_data.head()

The data has a different row for each passenger.

The next code cell defines and prints the values of three variables:
- `total` = total number of passengers who boarded the ship
- `survived` = number of passengers who survived the shipwreck
- `minors` = number of passengers under 18 years of age

Run the code cell without changes.

In [13]:
# Number of total passengers
total = 891
#len(titanic_data)
print(total)

# Number of passengers who survived
survived = 342
#(titanic_data.Survived == 1).sum()
print(survived)

# Number of passengers under 18
minors = 113
#(titanic_data.Age < 18).sum()
print(minors)

891
342
113


So,
- `total = 891` (there were 891 passengers on board the Titanic),
- `survived = 342` (342 passengers survived), and
- `minors = 113` (113 passengers were under the age of 18).

In the code cell below, replace the underlines (____) with code to calculate the values for two more variables:
- `survived_fraction` should be set to the fraction of passengers who survived the Titanic disaster.
- `minors_fraction` should be the fraction of passengers who were minors (under the age of 18).

For each variable, your answer should be a number between 0 and 1.

In [14]:
# TODO: Fill in the value of the survived_fraction variable
survived_fraction = survived / total

# Print the value of the variable
print(survived_fraction)

# TODO: Fill in the value of the minors_fraction variable
minors_fraction = minors / total

# Print the value of the variable
print(minors_fraction)

0.3838383838383838
0.12682379349046016


## 2. FUNCTIONS

### 2.1. Introduction to functions 

 A function is a block of code designed to perform a specific task.

 Every function is composed of two pieces: a header and body.

#### Header

The function header defines the name of the function and its argument(s).

- Every function header begins with def, which tells Python that we are about to define a function.
- Following, the function name.
- The argument is the name of the variable that will be used as input to the function. It is always enclosed in parentheses that apppear immediately after the name of the function. (Note that a function can also have no arguments, or it can have multiple arguments)
- For every function, the parentheses enclosing the function argument(s) must be followed by a colon `:`.

#### Body

The function body specifies the work that the function does.

- Every line of code in the function body must be indented exactly four spaces. You can do this by pushing the space bar four times, or by hitting the "Tab" button once on your keyboard.
- The function does its work by running all of the indented lines from top to bottom.
    - It takes the argument as input.
    - Then, the final line of code, called the return statement, just returns the function's output.

### 2.2. How to run (or "call") a function 

In [1]:
# Define the function
def add_three(input_var):
    output_var = input_var + 3
    return output_var

# Run the function with 10 as input
new_number = add_three(10)

# Check that the value is 13, as expected
print(new_number)

13


In the code cell, we run the function with 10 as the input value. We define a new variable new_number which is set to the output of the function.

In more detail,

- `add_three(10)` is the value that we get as output when we supply 10 as the value for input_var and call the `add_three()` function. When the function runs, it runs all of the code in its body, from top to bottom:
    - It first calculates `output_var = input_var + 3`, which sets `output_var = 13`.
    - The final line of code is the return statement, which returns the value of `output_var`, which is `13`.
- By setting `new_number = add_three(10)`, we set `new_number = 13`.

### 2.3. Naming functions

In the example above, the name of the function was selected for you. When naming your own functions, you should use only lowercase letters, with words separated by underscores instead of spaces.

### 2.4. A more complex example

Say you are helping a friend to calculate their weekly paycheck after taxes.

- They're in a 12% tax bracket (in other words, 12% of their salary is taken for taxes, and they only take home 88%), and
- They're paid hourly, at a rate of $15/hour.

The function below calculates the paycheck based on the number of hours worked. The function is more complicated than with the first example, because the function has more lines of code and comments. Similar to the example above, the function has a single argument (`num hours`). In the function body, we:

- Use the value for `num_hours` to specify the value for a new variable `pay_pretax`.
- Use the value of `pay_pretax` to specify the value for a new variable `pay_aftertax`.
- Return the value of the `pay_aftertax` variable.

In [2]:
def get_pay(num_hours):
    # Pre-tax pay, based on receiving $15/hour
    pay_pretax = num_hours * 15
    # After-tax pay, based on being in 12% tax bracket
    pay_aftertax = pay_pretax * (1 - .12)
    return pay_aftertax

We call this function the same way we called the first function. The next code cell calculates the paycheck, based on working 40 hours. (After taxes, it is $528.)

In [3]:
# Calculate pay based on working 40 hours
pay_fulltime = get_pay(40)
print(pay_fulltime)

528.0


To quickly calculate pay based on a different number of hours worked, you need to supply the function with a different number. For instance, say your friend works 32 hours. (Then, they get $422.40.)

In [4]:
pay_parttime = get_pay(32)
print(pay_parttime)

422.4


Because you wrote a function, you can calculate pay for different hours without having to rewrite all of the code in the calculations all over again.

Functions can help you to avoid errors in your code, and you save a lot of time. In general, when coding, you should aim to write as little as possible, because each time you type out a calculation, it's another opportunity to accidentally introduce a typo or error.

### 2.5. Variable "scope"

Variables defined inside the function body cannot be accessed outside of the function. For instance, the next code cell errors, because `pay_aftertax` only exists inside the function.

In [5]:
print(pay_aftertax)

NameError: name 'pay_aftertax' is not defined

For this reason, if you need any information from a function, you need to make sure that appears in the return statement at the end of the function.

We refer to a variable's scope as the part of the code where it is accessible. Variables defined inside a function (like `pay_aftertax`) have a local scope of that function only. However, as you've seen, variables defined outside all functions (like `pay_parttime`) have a global scope and can be accessed anywhere.

### 2.6. Functions with multiple arguments

To define a function with multiple arguments, you only need to add more arguments inside the parentheses in the function head and separate them with a comma.

We do this with the `get_pay_with_more_inputs()` function below, which calculates a weekly paycheck based on three arguments:

- `num_hours` - number of hours worked in one week
- `hourly_wage` - the hourly wage (in $/hour)
- `tax_bracket` - percentage of your salary that is removed for taxes

In [6]:
def get_pay_with_more_inputs(num_hours, hourly_wage, tax_bracket):
    # Pre-tax pay
    pay_pretax = num_hours * hourly_wage
    # After-tax pay
    pay_aftertax = pay_pretax * (1 - tax_bracket)
    return pay_aftertax

Then, to call the function, you need to provide one value for each input, again separated by a comma.

In the code cell below, we calculate the pay after taxes for someone who works 40 hours, makes $24/hour, and is in a 22% tax bracket.

In [7]:
higher_pay_aftertax = get_pay_with_more_inputs(40, 24, .22)
print(higher_pay_aftertax)

748.8000000000001


The following code cell gives the same result as when we ran `get_pay(40)`, because `hourly_wage` is set to 15, and `tax_bracket` is set to 12%, which lines up with how we designed `get_pay()`.

In [8]:
same_pay_fulltime = get_pay_with_more_inputs(40, 15, .12)
print(same_pay_fulltime)

528.0


Depending on how we plan to use this new function `get_pay_with_more_inputs()`, it can be more useful than the original function `get_pay()`, because it addresses more cases. Instead of potentially incorrectly assuming the hourly wage and tax bracket, the new function allows the user to specify the correct values. But, if you're sure the hourly wage and tax bracket won't need to change, the new function is just more complicated than necessary. In general, when defining functions, you'll need to consider how much flexibility you need, based on your use case.

### 2.7. Functions with no arguments

Note that it's possible to define function with no arguments, and that don't have a return statement. The `print_hello()` function in the code cell below is an example.

In [9]:
# Define the function with no arguments and with no return
def print_hello():
    print("Hello, you!")
    print("Good morning!")
    
# Call the function
print_hello()

Hello, you!
Good morning!


## Exercise 2

Run the next code cell without changes to set up the notebook.

In [15]:
# Set up the exercise
import math
from learntools.core import binder
binder.bind(globals())
from learntools.intro_to_programming.ex2 import *
print('Setup complete.')

ModuleNotFoundError: No module named 'learntools'

### Question 1

In the House Prices - Advanced Regression Techniques competition, you need to use information like the number of bedrooms and bathrooms to predict the price of a house. Inspired by this competition, you'll write your own function to do this.

In the next code cell, create a function `get_expected_cost()` that has two arguments:

- `beds` - number of bedrooms
- `baths` - number of bathrooms

It should return the expected cost of a house with that number of bedrooms and bathrooms. Assume that:

- the expected cost for a house with 0 bedrooms and 0 bathrooms is `80000`.
- each bedroom adds `30000` to the expected cost
- each bathroom adds `10000` to the expected cost.

For instance,

- a house with 1 bedroom and 1 bathroom has an expected cost of `120000`, and
- a house with 2 bedrooms and 1 bathroom has an expected cost of `150000`.


In [12]:
# TODO: Complete the function
def get_expected_cost(beds, baths):
    # value = ____
    value = 80000 + beds*30000 + baths*10000
    return value

get_expected_cost(1, 1)

120000

### Question 2

You are thinking about buying a home and want to get an idea of how much you will spend, based on the number of bedrooms and bathrooms. You are trying to decide between four different options:

- Option 1: house with two bedrooms and three bathrooms
- Option 2: house with three bedrooms and two bathrooms
- Option 3: house with three bedrooms and three bathrooms
- Option 4: house with three bedrooms and four bathrooms

Use the `get_expected_cost()` function you defined in question 1 to set `option_1`, `option_2`, `option_3`, and `option_4` to the expected cost of each option.

In [13]:
# TODO: Use the get_expected_cost function to fill in each value
# option_one = ____
option_one = get_expected_cost(2, 3)
# option_two = ____
option_two = get_expected_cost(3, 2)
# option_three = ____
option_three = get_expected_cost(3, 3)
# option_four = ____
option_four = get_expected_cost(3, 4)

print(option_one)
print(option_two)
print(option_three)
print(option_four)

170000
190000
200000
210000


### Question 3

You're a home decorator, and you'd like to use Python to streamline some of your work. Specifically, you're creating a tool that you intend to use to calculate the cost of painting a room.

As a first step, define a function `get_cost()` that takes as input:

- `sqft_walls` = total square feet of walls to be painted
- `sqft_ceiling` = square feet of ceiling to be painted
- `sqft_per_gallon` = number of square feet that you can cover with one gallon of paint
- `cost_per_gallon` = cost (in dollars) of one gallon of paint

It should return the cost (in dollars) of putting one coat of paint on all walls and the ceiling. Assume you can buy the exact amount of paint that you need, so you can buy partial gallons (e.g., if you need 7.523 gallons, you can buy that exact amount, instead of needing to buy 8 gallons and waste some paint). Do not round your answer.

In [14]:
# TODO: Finish defining the function
def get_cost(sqft_walls, sqft_ceiling, sqft_per_gallon, cost_per_gallon):
    # cost = ____
    cost = ((sqft_walls + sqft_ceiling) / sqft_per_gallon) * cost_per_gallon
    return cost

### Question 4

Use the `get_cost()` function you defined in Question 3 to calculate the cost of applying one coat of paint to a room with:

- 432 square feet of walls, and
- 144 square feet of ceiling.

Assume that one gallon of paint covers 400 square feet and costs $15. As in Question 3, assume you can buy partial gallons of paint. Do not round your answer.

In [20]:
# TODO: Set the project_cost variable to the cost of the project
# project_cost = ____
project_cost = get_cost(432, 144, 400, 15)
print(project_cost)

21.599999999999998


### Question 5

Now say you can no longer buy fractions of a gallon. (For instance, if you need 4.3 gallons to do a project, then you have to buy 5 gallons of paint.)

With this new scenario, you will create a new function `get_actual_cost()` that uses the same inputs and calculates the cost of your project.

One function that you'll need to use to do this is `math.ceil()`. We demonstrate usage of this function in the code cell below. It takes as a number as input and rounds the number up to the nearest integer.

Run the next code cell to test this function for yourself. Feel free to change the value of `test_value` and make sure `math.ceil()` returns the number you expect.

In [18]:
test_value = 2.17

rounded_value = math.ceil(test_value)
print(rounded_value)

3


Use the next code cell to define the function `get_actual_cost()`. You'll need to use the `math.ceil()` function to do this.

When answering this question, note that it's completely valid to define a function that makes use of another function. For instance, we can define a function `round_up_and_divide_by_three()` that makes use of the `math.ceil()` function:

def round_up_and_divide_by_three(num): \
    new_value = math.ceil(num) \
    final_value = new_value / 3 \
    return final_value \

In [24]:
def get_actual_cost(sqft_walls, sqft_ceiling, sqft_per_gallon, cost_per_gallon):
    # cost = ____
    gallons = math.ceil((sqft_walls + sqft_ceiling) / sqft_per_gallon)
    cost = gallons * cost_per_gallon
    return cost

## 3. DATA TYPES

### 3.1. Introduction to data types

Whenever you create a variable in Python, it has a value with a corresponding data type. 

Data types are important, because they determine what kinds of actions you can do with them.
To avoid errors, we need to make sure that the actions match the data types that we have.

### 3.2. Integers

Integers are numbers without any fractional part and can be positive (1, 2, 3, ...), negative (-1, -2, -3, ...), or zero (0).

In the code cell below, we set a variable x to an integer. We then verify the data type with `type()`, and need only pass the variable name into the parentheses.

In the output , `<class 'int'>` refers to the integer data type.

In [1]:
x = 14
print(x)
print(type(x))

14
<class 'int'>


### 3.3. Floats

Floats are numbers with fractional parts. They can have many numbers after decimal.

In [2]:
nearly_pi = 3.141592653589793238462643383279502884197169399375105820974944
print(nearly_pi)
print(type(nearly_pi))

3.141592653589793
<class 'float'>


We can also specify a float with a fraction.

In [3]:
almost_pi = 22/7
print(almost_pi)
print(type(almost_pi))

3.142857142857143
<class 'float'>


One function that is particularly useful for fractions is the `round()` function. It lets you round a number to a specified number of decimal places.

In [4]:
# Round to 5 decimal places
rounded_pi = round(almost_pi, 5)
print(rounded_pi)
print(type(rounded_pi))

3.14286
<class 'float'>


Whenever you write an number with a decimal point, Python recognizes it as a float data type.

For instance, 1. (or 1.0, 1.00, etc) will be recognized as a float. This is the case, even though these numbers technically have no fractional part!

### 3.4. Booleans

Booleans represent one of two values: `True` or `False`. In the code cell below, `z_one` is set to a boolean with value `True`.

In [5]:
z_one = True
print(z_one)
print(type(z_one))

True
<class 'bool'>


Next, `z_two` is set to a boolean with value `False`.

In [6]:
z_two = False
print(z_two)
print(type(z_two))

False
<class 'bool'>


Booleans are used to represent the truth value of an expression. Since `1 < 2` is a true statement, `z_three` takes on a value of `True`.

In [7]:
z_three = (1 < 2)
print(z_three)
print(type(z_three))

True
<class 'bool'>


Similarly, since `5 < 3` is a false statement, `z_four` takes on a value of `False`.

In [8]:
z_four = (5 < 3)
print(z_four)
print(type(z_four))

False
<class 'bool'>


We can switch the value of a boolean by using `not`. So, `not True` is equivalent to `False`, and `not False` becomes `True`.

In [9]:
z_five = not z_four
print(z_five)
print(type(z_five))

True
<class 'bool'>


### 3.5. Strings

The string data type is a collection of characters (like alphabet letters, punctuation, numerical digits, or symbols) contained in quotation marks. Strings are commonly used to represent text.

In [10]:
w = "Hello, Python!"
print(w)
print(type(w))

Hello, Python!
<class 'str'>


You can get the length of a string with `len()`. `"Hello, Python!"` has length 14, because it has 14 characters, including the space, comma, and exclamation mark. Note that the quotation marks are not included when calculating the length.

In [11]:
print(len(w))

14


One special type of string is the empty string, which has length zero.

In [12]:
shortest_string = ""
print(type(shortest_string))
print(len(shortest_string))

<class 'str'>
0


If you put a number in quotation marks, it has a string data type.

In [13]:
my_number = "1.12321"
print(my_number)
print(type(my_number))

1.12321
<class 'str'>


If we have a string that is convertible to a float, we can use `float()`.

This won't always work! For instance, we can convert `"10.43430"` and `"3"` to floats, but we cannot convert `"Hello, Python!"` to a float.


In [14]:
also_my_number = float(my_number)
print(also_my_number)
print(type(also_my_number))

1.12321
<class 'float'>


Just like you can add two numbers (floats or integers), you can also add two strings. It results in a longer string that combines the two original strings by concatenating them.

In [15]:
new_string = "abc" + "def"
print(new_string)
print(type(new_string))

abcdef
<class 'str'>


Note that it's not possible to do subtraction or division with two strings. You also can't multiply two strings, but you can multiply a string by an integer. This again results in a string that's just the original string concatenated with itself a specified number of times.

In [16]:
newest_string = "abc" * 3
print(newest_string)
print(type(newest_string))

abcabcabc
<class 'str'>


Note that you cannot multiply a string by a float! Trying to do so will return an error.

In [17]:
will_not_work = "abc" * 3.

TypeError: can't multiply sequence by non-int of type 'float'

In the error, the "sequence" is the string "abc", and the "non-int of type 'float'" is the float (3.). So, the error message can be reworded to say "can't multiply string by float".

## Exercise 3

Run the next code cell without changes to set up the notebook.

In [18]:
# Set up the exercise
from learntools.core import binder
binder.bind(globals())
from learntools.intro_to_programming.ex3 import *
print('Setup complete.')

ModuleNotFoundError: No module named 'learntools'

### Question 1

You have seen how to convert a float to an integer with the `int()` function. Try this out yourself by running the code cell below.

In [19]:
# Define a float
y = 1.
print(y)
print(type(y))

# Convert float to integer with the int function
z = int(y)
print(z)
print(type(z))

1.0
<class 'float'>
1
<class 'int'>


In this case, the float you are using has no numbers after the decimal.

- But what happens when you try to convert a float with a fractional part to an integer?
- How does the outcome of the `int()` function change for positive and negative numbers?

Use the next code cell to investigate and answer these questions. Feel free to add or remove any lines of code -- it is your workspace!


In [20]:
# Uncomment and run this code to get started!
print(int(1.2321))
print(int(1.747))
print(int(-3.94535))
print(int(-2.19774))

1
1
-3
-2


Negative floats are always rounded UP to the closest integer (for instance, both -1.1 and -1.9 are rounded up to -1). Positive floats are always rounded DOWN to the closest integer (for instance, 2.1 and 2.9 are rounded down to 2).

### Question 2

In the tutorial, you learned about booleans (which can take a value of `True` or `False`), in addition to integers, floats, and strings. For this question, your goal is to determine what happens when you multiply a boolean by any of these data types. Specifically,

- What happens when you multiply an integer or float by `True`? What happens when you multiply them by `False`? How does the answer change if the numbers are positive or negative?
- What happens when you multiply a string by `True`? By `False`?

Use the next code cell for your investigation. 

In [2]:
# Uncomment and run this code to get started!
print(3 * True)
print(-3.1 * True)
print(type("abc" * False))
print(len("abc" * False))

3
-3.1
<class 'str'>
0


When you multiple an integer or float by a boolean with value `True`, it just returns that same integer or float (and is equivalent to multiplying by 1). If you multiply an integer or float by a boolean with value `False`, it always returns 0. This is true for both positive and negative numbers. If you multiply a string by a boolean with value `True`, it just returns that same string. And if you multiply a string by a boolean with value `False`, it returns an empty string (or a string with length zero).

### Question 3

In this question, you will build off your work from the previous exercise to write a function that estimates the value of a house.

Use the next code cell to create a function `get_expected_cost()` that takes as input three variables:

- `beds` - number of bedrooms (data type float)
- `baths` - number of bathrooms (data type float)
- `has_basement` - whether or not the house has a basement (data type boolean)

It should return the expected cost of a house with those characteristics. Assume that:

- the expected cost for a house with 0 bedrooms and 0 bathrooms, and no basement is 80000,
- each bedroom adds 30000 to the expected cost,
- each bathroom adds 10000 to the expected cost, and
- a basement adds 40000 to the expected cost.

For instance,

- a house with 1 bedroom, 1 bathroom, and no basement has an expected cost of 80000 + 30000 + 10000 = 120000. This value will be calculated with `get_expected_cost(1, 1, False)`.
- a house with 2 bedrooms, 1 bathroom, and a basement has an expected cost of 80000 + 2*30000 + 10000 + 40000 = 190000. This value will be calculated with `get_expected_cost(2, 1, True)`.

In [ ]:
# TODO: Complete the function
def get_expected_cost(beds, baths, has_basement):
    # value = ____
    value = 80000 + beds*30000 + baths*10000 + has_basement*40000
    return value

### Question 4

We'll continue our study of boolean arithmetic. For this question, your task is to provide a description of what happpens when you add booleans.

Use the next code cell for your investigation. Feel free to add or remove any lines of code - use it as your workspace!

In [3]:
print(False + False)
print(True + False)
print(False + True)
print(True + True)
print(False + True + True + True)

0
1
1
2
3


When you add booleans, adding `False` is equivalent to adding 0, and adding `True` is equivalent to adding 1.

### Question 5

You own an online shop where you sell rings with custom engravings. You offer both gold plated and solid gold rings.

- Gold plated rings have a base cost of $50, and you charge $7 per engraved unit.
- Solid gold rings have a base cost of $100, and you charge $10 per engraved unit.
- Spaces and punctuation are counted as engraved units.

Write a function `cost_of_project()` that takes two arguments:

- `engraving` - a Python string with the text of the engraving
- `solid_gold` - a Boolean that indicates whether the ring is solid gold

It should return the cost of the project. This question should be fairly challenging, and you may need a hint.

In [1]:
def cost_of_project(engraving, solid_gold):
    # cost = ____
    cost = solid_gold * (100 + 10 * len(engraving)) + (not solid_gold) * (50 + 7 * len(engraving))
    return cost

Run the next code cell to calculate the cost of engraving `Charlie+Denver` on a solid gold ring.

In [2]:
project_one = cost_of_project("Charlie+Denver", True)
print(project_one)

240


Use the next code cell to calculate the cost of engraving `08/10/2000` on a gold plated ring.

In [3]:
project_two = cost_of_project("08/10/2000", False)
print(project_two)

120


## 4. CONDITIONS AND CONDITIONAL STATEMENTS

## Exercise 4

## 5. INTRO TO LISTS

## Exercise 5